schema_version = "1.0.0"

id = "vrchat_outfit_helper"
version = "1.0.1"
name = "VRChat Outfit Helper"
tagline = "Simplifies clothing rigging for VRChat avatars"
maintainer = "Marek Hanzelka"

type = "add-on"

website = "https://github.com/Maro-3D/VRChat-Outfit-Helper/tree/main"

tags = ["Rigging"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
