schema_version = "1.0.0"

id = "vertex_group_assistant"
version = "1.0.2"
name = "Vertex Group Assistant"
tagline = "Simplifies clothing rigging for avatars"
maintainer = "Marek Hanzelka"

type = "add-on"

website = "https://github.com/Maro-3D/VRChat-Outfit-Helper/tree/main"

tags = ["Rigging"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
